export const LETTERS_NEXT = 'LETTERS/LETTERS_NEXT';
export const LETTERS_PREV = 'LETTERS/LETTERS_PREV';
export const LETTER_COMPLETE = 'LETTERS/LETTER_COMPLETE';

export const TRAINING_BEGIN = 'TRAINING/TRAINING_BEGIN';
export const TRAINING_CLOSE = 'TRAINING/TRAINING_CLOSE';
export const DESTROY_LETTER = 'TRAINING/DESTROY_LETTER';
export const GENERATE_LETTER = 'TRAINING/GENERATE_LETTER';
export const LETTER_CATH = 'TRAINING/LETTER_CATH';