export const LETTERS_NEXT = 'LETTERS/LETTERS_NEXT';
export const LETTERS_PREV = 'LETTERS/LETTERS_PREV';
export const COMPLETE = 'LETTERS/COMPLETE';

export const TRAINING_BEGIN = 'TRAINING/TRAINING_BEGIN';
export const TRAINING_END = 'TRAINING/TRAINING_END';
export const DESTROY_LETTER = 'TRAINING/DESTROY_LETTER';
export const GENERATE_LETTER = 'TRAINING/GENERATE_LETTER';
export const LETTER_CATH = 'TRAINING/LETTER_CATH';